server:
  port: ${PORT:7778}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: ${ACTPORT:0}
spring:
  application:
    name: ${NAME:account-service}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password: dev
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
